version: '3'
services:
  sphinx:
    build:
      context: ./.
      dockerfile: ./Dockerfile
    container_name: sphinx
    tty: true
    ports:
      - "8888:8888" # Needed for sphinx-autobuild
    volumes:
      - ./:/docs
    networks:
      - sphinx-docs
networks:
  sphinx-docs:
    driver: bridge
    
